### ISSUE TITLE
Epic: Convert to a full service with API

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/language#24]
This epic is composed of the following:
* [ ] Add language component - #8
* [ ] Add language and name generator support to language component  - #18 
* [ ] Update all library calls to use the db instead of reading from the filesystem  - #23
* [ ] Create a REST API for the language app - #22
* [ ] Update CLI to support both syntagmata and markov generation #16
